# Generated by Django 2.2.3 on 2020-08-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='emp_name')),
                ('age', models.IntegerField(verbose_name='emp_age')),
                ('salary', models.FloatField(verbose_name='emp_salary')),
                ('desig', models.CharField(max_length=50, verbose_name='emp_designation')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='stud_name')),
                ('age', models.IntegerField(verbose_name='stud_age')),
                ('fees', models.FloatField(verbose_name='stud_fees')),
                ('course', models.CharField(max_length=50, verbose_name='stud_course')),
            ],
        ),
    ]
